### ISSUE TITLE
Deploy application on Heroku.

### ISSUE THREAD

**Issue by sunnyshahabuddin** [sunnyshahabuddin/neeto-ui-challenge#7]

**Comment by sunnyshahabuddin** [comment]
Deployed at [https://sunnyshahabuddin-neeto-ui.herokuapp.com/](https://sunnyshahabuddin-neeto-ui.herokuapp.com/)

Can be logged in using:
Username : oliver@example.com
Password : welcome

@yedhink  Please review.

**Comment by sunnyshahabuddin** [comment]
Deployed at https://sunnyshahabuddin-neeto-ui.herokuapp.com/
Can be logged in using:
Username : oliver@example.com
Password : welcome

@yedhink  Please review.

**Comment by yedhink** [comment]
@sunnyshahabuddin LGTM. You can mark this task as completed and continue with the next one.

**Comment by sunnyshahabuddin** [comment]
Thank you Yedhin.
